app = "subsacip-api"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  HOST = "0.0.0.0"
  DATABASE_SSL = "true"
  TYPEORM_SYNC = "true"
  TYPEORM_LOGGING = "false"
  SEED_DATABASE = "true"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
